# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sybil & Dave
description: >- # this means to ignore newlines until "baseurl:"
  Sybil & Dave Wedding Site
baseurl: "/bay" # the subpath of the site
url: "https://dlesomewhere.github.io/"
og_image: /assets/img/main-image.jpg
google_analytics: "XXX"

header:
  pages:
    - name: Home
      slug: /
    - name: On The Day
      slug: /on_the_day

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
