# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sybil & Dave
description: Sybil & Dave's Wedding
url: "https://www.weirgettingmarried.co.uk"
og_image: /assets/img/color_factory.jpg

header:
  pages:
    - name: On The Day
      slug: /on_the_day
    - name: FAQ
      slug: /faq

footer:
  show_powered_by: false

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
